### ISSUE TITLE
Option to turn off profanity filter completely or to bypassing it with permission?

### ISSUE THREAD

**Issue by Thunder33345** [Awzaw/RolePlay#1]

**Comment by Awzaw** [comment]
The latest version of [AntiSpamPro](https://poggit.pmmp.io/p/AntiSpamPro) has permissions for commands and bypass. EDIT: I also need to update so the API takes player perms into account...

**Comment by Awzaw** [comment]
https://poggit.pmmp.io/p/RolePlay

**Comment by Thunder33345** [comment]
personally i think it should be handled separately not entirely reliant on some other plugin

**Comment by Awzaw** [comment]
You can use the plugin without ASP if you don't want filtering... And copying the ASP filtering code into both roleplay and factionspro would be silly.

**Comment by Thunder33345** [comment]
by that i meant just have a separate perm like roleplay.prof.bypass will make role play plugin not execute prof checks

**Comment by Awzaw** [comment]
I see, ok

**Comment by Awzaw** [comment]
Actually, seems weirder having a roleplay perm that only does anything if ASP is installed :-/ and why would anyone be subject to filtering in chat but not in roleplay, or vice-versa?

**Comment by Thunder33345** [comment]
yes, that feature would rarely get utilised but it may create inflexibility if shall someone wished to allow profanity only in rp or the other way around
